### ISSUE TITLE
Dependency on acorn resolves to 1.0.1 which breaks the require to 'acorn/util/walk' in index.js

### ISSUE THREAD

**Issue by martijn500** [ForbesLindesay/with#5]
In version 1.0.1 of acorn there's no util folder.
The acorn dependency is resolved in a weird way, because ^0.11.0 shouldn't resolve to 1.0.1 am I right? 
Might be an issue with acorn..?

**Comment by ForbesLindesay** [comment]
This is because your npm is very out of date.  If you update to the latest version of npm and then re-install with it should be fixed.
